-- CREATE SCHEMA Bank;

CREATE TABLE Bank.Vartotojas(
    Id          INTEGER PRIMARY KEY     NOT NULL
                GENERATED ALWAYS AS IDENTITY (START WITH 100 INCREMENT BY 1),
    Vardas      CHAR (15)               NOT NULL,
    Pavarde     VARCHAR (30)            NOT NULL,
    Gimimo_data DATE                    NOT NULL 
                CONSTRAINT Amzius CHECK (EXTRACT(YEAR FROM AGE(CURRENT_DATE, Gimimo_data)) >= 18)
    --PRIMARY KEY (Id)
);


CREATE TABLE Bank.Bankas(
    Id          SMALLINT                NOT NULL 
                GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    Pavadinimas CHAR (20)               NOT NULL 
                CONSTRAINT BankoPavadinimas UNIQUE,
    Kapitalas   BIGINT,
    Adresas     CHAR (70),
    Reitingas   CHAR(3) DEFAULT 'N/A' 
                CONSTRAINT ReitingoDydis CHECK (Reitingas = 'N/A' OR (CAST (Reitingas AS INTEGER) > 0 AND CAST (Reitingas AS INTEGER) <= 5)),
    PRIMARY KEY (Id)
);

CREATE TABLE Bank.Saskaita(
    Id          integer                 NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 10000 INCREMENT BY 1),
    Vartotojas  SMALLINT                NOT NULL,
    Balansas    INTEGER 
                CONSTRAINT BalansoDydis CHECK (Balansas >= 0) DEFAULT 0,
    Bankas      SMALLINT                NOT NULL,
    Tipas       CHAR (20) DEFAULT 'paprasta',
    PRIMARY KEY(id),
    CONSTRAINT IVartotoja FOREIGN KEY (Vartotojas) REFERENCES Bank.Vartotojas ON DELETE CASCADE,
    CONSTRAINT IBanka FOREIGN KEY (Bankas) REFERENCES Bank.Bankas ON DELETE CASCADE
);

CREATE TABLE Bank.Kortele(
    Id          BIGINT                  NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 555544440000 INCREMENT BY 1),
    Limitas     INTEGER
                CONSTRAINT MaxLimitas CHECK(Limitas < 1000000000),
    Galiojimas  DATE 
                CONSTRAINT GaliojimoLaikas CHECK(EXTRACT (YEAR FROM AGE(Galiojimas, CURRENT_DATE)) <= 4),
    PRIMARY KEY(id)
);
CREATE TABLE Bank.KortelesSaskaita(
    Id          BIGINT                  NOT NULL,
    Saskaita    INTEGER                 NOT NULL
                CONSTRAINT KortelesSaskaitosNr UNIQUE, 
    PRIMARY KEY(id, Saskaita),
    CONSTRAINT ISaskaita FOREIGN KEY (Saskaita) REFERENCES Bank.Saskaita ON DELETE CASCADE
);

CREATE TABLE Bank.KortelesGaliojimoKeitimas(
    Id               BIGINT                  NOT NULL,
    SenasGaliojimas  DATE,
    NaujasGaliojimas DATE,
    KeitimoLaikas    DATE,
    CONSTRAINT GaliojimoPakeitimas CHECK (SenasGaliojimas < NaujasGaliojimas)
);

CREATE TABLE Bank.Paslauga(
    Id          SMALLINT                NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    Pavadinimas CHAR(50),
    Kaina       SMALLINT DEFAULT 0,
    PRIMARY KEY (Id)
);

CREATE TABLE Bank.BankoPaslaugos(
    BankoId     SMALLINT,
    PaslaugosId SMALLINT,
    PRIMARY KEY (BankoId, PaslaugosId),
    CONSTRAINT IPaslaugas FOREIGN KEY (PaslaugosId) REFERENCES Bank.Paslauga ON DELETE CASCADE
);

